angular
  .module(
    'Module.emailpro',
    [
      'ovh-utils-angular',
      'ngRoute',
      'ui.bootstrap',
      'ngSanitize',
      'ng.ckeditor',
      'emailProConstants',
      'emailProControllers',
      'emailProFilters',
      'emailProRoutes',
      'emailProServices',
    ],
  );
