angular
  .module(
    'Module.emailpro',
    [
      'ovh-utils-angular',
      'ngRoute',
      'ui.bootstrap',
      'ngSanitize',
      'ng.ckeditor',
      'emailproConstants',
      'emailproControllers',
      'emailproFilters',
      'emailproRoutes',
      'emailproServices',
    ],
  );
